# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EUR_USD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(unique=True)),
                ('ask_o', models.FloatField(blank=True, max_length=10, null=True)),
                ('ask_h', models.FloatField(blank=True, max_length=10, null=True)),
                ('ask_l', models.FloatField(blank=True, max_length=10, null=True)),
                ('ask_c', models.FloatField(blank=True, max_length=10, null=True)),
                ('bid_o', models.FloatField(blank=True, max_length=10, null=True)),
                ('bid_h', models.FloatField(blank=True, max_length=10, null=True)),
                ('bid_l', models.FloatField(blank=True, max_length=10, null=True)),
                ('bid_c', models.FloatField(blank=True, max_length=10, null=True)),
                ('v', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
