# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EUR_USD',
        ),
    ]
