#!/bin/bash


echo "trying launch oanda mget..."

#source /export/crawlspace/anaconda2/bin/activate
#cd /home/tingle/git/eab/tools/

exec setuidgid tingle /export/crawlspace/eab/tools/oanda_mget_all.py  2>&1

