# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('sym', models.CharField(max_length=10)),
                ('o', models.FloatField(blank=True, max_length=5, null=True)),
                ('h', models.FloatField(blank=True, max_length=5, null=True)),
                ('l', models.FloatField(blank=True, max_length=5, null=True)),
                ('c', models.FloatField(blank=True, max_length=5, null=True)),
                ('v', models.IntegerField()),
            ],
        ),
    ]
