# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20170403_0558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temptablemodel',
            unique_together=set([('sym', 'dt')]),
        ),
    ]
