#!/bin/bash


echo "trying launch Xvfb vnc.."

exec 2>&1
exec setuidgid yuting x11vnc -create \
			     -env FD_PROG=/usr/bin/fluxbox  \
			     -env X11VNC_FINDDISPLAY_ALWAYS_FAILS=1  \
			     -env X11VNC_CREATE_GEOM=${1:-800x600x16} \
			     -gone 'killall Xvfb'   \
			     -bg -nopw -loop100

