#!/bin/bash


echo "trying launch them..."
sleep 1
#source /home/tingle/eabot/bin/activate
cd /export/crawlspace/eab/forexsys

exec 2>&1
exec /export/crawlspace/anaconda2/bin/uwsgi -M --log-master --die-on-term  --http :80 --module forexsys.wsgi

