# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempTable',
            new_name='TempTableModel',
        ),
    ]
