# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_eur_usd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EUR_USD',
        ),
    ]
